/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_laputa_fmod_FmodHelper */

#ifndef _Included_com_laputa_fmod_FmodHelper
#define _Included_com_laputa_fmod_FmodHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_laputa_fmod_FmodHelper_MODE_NORMAL
#define com_laputa_fmod_FmodHelper_MODE_NORMAL 0L
#undef com_laputa_fmod_FmodHelper_MODE_LOLI
#define com_laputa_fmod_FmodHelper_MODE_LOLI 1L
#undef com_laputa_fmod_FmodHelper_MODE_DASHU
#define com_laputa_fmod_FmodHelper_MODE_DASHU 2L
#undef com_laputa_fmod_FmodHelper_MODE_KONGLING
#define com_laputa_fmod_FmodHelper_MODE_KONGLING 3L
#ifdef __cplusplus
}
#endif
#endif
